const assert = require('node:assert/strict');
const matcher = require('../matching.js');
const perfume = (id, note_keys) => ({ id, name: id, note_keys });
const close = (a,b) => assert(Math.abs(a-b) < 1e-12, `${a} != ${b}`);
const target = perfume('target', ['amber','vanilla']);
const a = perfume('a', ['amber','vanilla']);
const b = perfume('b', ['amber','coffee']);
const c = perfume('c', ['rose','musk']);
const result = matcher.assess(target,[a,b]);
close(result.score, Math.sqrt(3)/2);
assert.equal(result.title,'High overlap');
assert.equal(result.percentage,87);
assert.deepEqual(result.shared,['amber','vanilla']);
assert.deepEqual(result.different,[]);
assert.equal(result.profile.counts.get('amber'),2);
assert.equal(result.profile.counts.get('vanilla'),1);
assert.equal(matcher.assess(target,[a]).available,false);
assert.equal(matcher.assess(target,[a,a]).selectedCount,1);
assert.equal(matcher.assess(target,[target,a]).available,false);
assert.equal(matcher.assess(target,[a,perfume('empty',[])]).score,null);
assert.equal(matcher.assess(perfume('empty-target',[]),[a,b]).available,false);
assert.equal(matcher.assess(target,[c,perfume('d',['rose'])]).score,0);
close(matcher.assess(target,[a,perfume('copy',a.note_keys)]).score,1);
assert.equal(matcher.assess(target,[a,b,c]).score,matcher.assess(target,[c,b,a]).score);
assert.equal(matcher.assess(target,[a,b,a]).score,result.score);
assert(matcher.assess(target,[a,b,c]).score < result.score);
const duplicatePattern = matcher.assess(target,[a,b,perfume('a2',a.note_keys),perfume('b2',b.note_keys)]);
close(duplicatePattern.score,result.score);
assert.equal(duplicatePattern.contributingCount,4);
const short = perfume('short',['amber']), long = perfume('long',['rose','musk','coffee','vanilla']);
const profile = matcher.buildProfile([short,long]);
close(profile.weights.get('amber'),.5);
close(profile.weights.get('rose'),.25);
assert.equal(profile.counts.get('rose'),1);
assert.deepEqual(matcher.notes(perfume('alias',['Cedar Wood','cedarwood',' AMBER ',null,''])),['amber','cedarwood']);
assert.equal(matcher.assess(perfume('rose',['rose']),[perfume('r1',['red rose']),perfume('r2',['red rose'])]).score,0);
assert.equal(matcher.assess(perfume('musk',['musk']),[perfume('m1',['white musk']),perfume('m2',['white musk'])]).score,0);
assert.equal(matcher.percentage(0),0);
assert.equal(matcher.percentage(1),100);
assert.equal(matcher.percentage(.4743),47);
assert.equal(matcher.percentage(.475),48);
assert.equal(matcher.percentage(null),null);
assert.equal(matcher.percentage(NaN),null);
assert.equal(matcher.percentage(Infinity),null);
assert.equal(matcher.assess(target,[a]).percentage,null);
assert.equal(matcher.assess(target,[c,perfume('d',['rose'])]).percentage,0);
const withMissing=matcher.assess(target,[a,b,perfume('missing',[])]);
assert.equal(withMissing.contributingCount,2); assert.equal(withMissing.selectedCount,3);
assert.equal(withMissing.score,result.score);
assert.equal(matcher.explain(result),'Amber appears in both of your favorites. All its listed notes appear somewhere in your collection.');
const novel=matcher.assess(perfume('novel',['amber','caramel']),[a,b,c]);
assert.equal(matcher.explain(novel),'Amber appears in 2 of your 3 favorites. This one adds caramel.');
assert.equal(matcher.explain(matcher.assess(target,[c,perfume('d',['rose'])])),'None of its listed notes appear in your favorites. This one lists amber and vanilla.');
assert.equal(matcher.explain(matcher.assess(target,[a])),'Choose at least two perfumes you love to build your profile.');
const catalog=require('../data/app/catalog.json');
const find=(brand,name)=>catalog.perfumes.find(p=>p.brand===brand&&p.name===name);
const darker=find('HMNS','Darker Shades of Orgsm'),addict=find('HMNS','Addict'),fantasy=find('Aoera','Fantasy');
const actual=matcher.assess(darker,[addict,fantasy]);
assert.deepEqual(actual.shared.slice(0,1),['amber']);
assert.equal(actual.profile.counts.get('amber'),2);
assert.equal(actual.profile.counts.get('patchouli'),1);
assert.deepEqual(actual.different,['apple','cypriol','orange blossom','pepper','vetiver']);
assert(actual.score>0&&actual.score<1);
assert.equal(actual.percentage,47);
assert.equal(actual.title,'Medium overlap');
assert.equal(matcher.category(.70),'High overlap');
assert.equal(matcher.category(.35),'Medium overlap');
assert.equal(matcher.category(.349),'Low overlap');
console.log('Profile checks passed: cosine, equal perfume weight, recurrence, order, duplicate exclusion, all-favorite influence, missing notes, fixed copy, and real catalog.');
console.log('Real profile:', actual.score.toFixed(4), actual.title, matcher.explain(actual));
